name: Build & Deploy - Dev

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/phyusinthaw09/payment-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tag version
        id: tag-version
        run: echo "version=${{ github.run_number }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish -c Release -o publish --no-build

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -f deployment/Dockerfile.dev \
            -t ${{ env.IMAGE_NAME }}:${{ steps.tag-version.outputs.version }} \
            .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.tag-version.outputs.version }}

      - name: Checkout Kustomize chart Repository
        uses: actions/checkout@v4
        with:
          repository: zawthanoo/workshop-apps
          path: deployment
          token: ${{ secrets.MY_GITHUB_TOKEN }}
